### ISSUE TITLE
COPY Oracle to postgresql fails

### ISSUE THREAD

**Issue by pkej** [visulate/visulate-ora2pg#103]
`
DBD::Pg::db do failed: ERROR:  could not open extension control file "/usr/share/postgresql/14/extension/oracle_fdw.control": No such file or directory at /usr/local/lib/perl5/site_perl/5.34.0/Ora2Pg.pm line 19321.
[2022-08-15 14:57:10] FATAL: ERROR:  could not open extension control file "/usr/share/postgresql/14/extension/oracle_fdw.control": No such file or directory
Aborting export...
`

It seems that the postgresql extension is missing, I've been going back to 1.1.4 and the error is in all, and in 1.1.3 the config file fails with:

`Undefined subroutine &Ora2Pg::ReadLine called at /usr/local/lib/perl5/site_perl/5.32.0/Ora2Pg.pm line 19310.
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle (DESCRIPTION=(ADDRESS=(PORT=1521)(HOST=maoracle30.felles.ds.nrk.no)(PROTOCOL=tcp))(CONNECT_DATA=(SID=TEKO))) at /usr/local/lib/perl5/site_perl/5.32.0/Ora2Pg.pm line 19310.
ora2pg complete
`

**Comment by pkej** [comment]
I went back to 1.1.3 and created a config in it by itself, and now I'm copying the data without problems.

**Comment by pkej** [comment]
It works in 1.1.3 (e.g. I have a database in Oracle which I directly transfer to PostgreSQL).

**Comment by pgoldtho** [comment]
I think that's a feature in the latest update of Ora2Pg. By default Ora2Pg will attempt to use the FDW extension to improve data migration performance - see [Ora2PG now supports oracle_fdw to increase the data migration speed](https://www.migops.com/blog/2021/07/01/ora2pg-now-supports-oracle_fdw-to-increase-the-data-migration-speed/). 

Follow the [oracle_fdw install instructions](https://github.com/laurenz/oracle_fdw#5-installation-requirements) to enable this. Alternatively, use the Show advanced settings option of the UI to display and disable the FDW_SERVER and ORACLE_FDW_TRANSFORM parameters.
