### ISSUE TITLE
Hello, this tool is very good and has helped me a lot. However, I found that the WEB page has no login access control, and anyone can access it. This is not safe. Can add a control method such as basic authentication？

### ISSUE THREAD

**Issue by XyxH** [visulate/visulate-ora2pg#105]
Hello, this tool is very good and has helped me a lot. However, I found that the WEB page has no login access control, and anyone can access it. This is not safe. Can add a control method such as basic authentication？

**Comment by pgoldtho** [comment]
It's intended for deployment on a laptop or a server inside a corporate firewall. I use it on a Google Cloud VM that has no external IP address and then access the UI from another VM running Chrome Remote Desktop (https://cloud.google.com/architecture/chrome-desktop-remote-on-compute-engine)

Incidentally, it saves the database DSN but not credentials as described in this document:

https://github.com/visulate/visulate-ora2pg/blob/main/specs/auth_requirements.md
