### ISSUE TITLE
How to view ora2pg-conf.json file?

### ISSUE THREAD

**Issue by koteshgangavarapu** [visulate/visulate-ora2pg#108]
Hi,
We are currently comparing the DDL scripts generated by Visulate-ora2pg and DDL scripts generated by Ora2Pg CLI. There seems to some differences between those two. 
We have compared the configuration parameters between CLI and Visulate-ora2pg GUI and they match.  
Is there a way to view the contents of the ora2pg-conf.json.enc file so that we can compare the configuration parameters.?

Thanks

**Comment by pgoldtho** [comment]
Yes. Press the `EXPORT` button at the top of the screen (between SAVE and RUN)

**Comment by koteshgangavarapu** [comment]
Thank you very much.
