### ISSUE TITLE
Document FDW_SERVER and ORACLE_FDW_TRANSFORM

### ISSUE THREAD

**Issue by oraculix** [visulate/visulate-ora2pg#113]
Quote from #103:

> By default Ora2Pg will attempt to use the FDW extension to improve data migration performance - see [Ora2PG now supports oracle_fdw to increase the data migration speed](https://www.migops.com/blog/2021/07/01/ora2pg-now-supports-oracle_fdw-to-increase-the-data-migration-speed/).

Unfortunately, managed (Cloud) services, e.g. Azure Flexible Server for PG, do not provide oracle_fdw and prohibit the installation of extensions. Probably, more and more users will run into this issue in the future.

Therefore I propose to add this info from #103 to the documentation:

>Alternatively, use the Show advanced settings option of the UI to display and disable the FDW_SERVER and ORACLE_FDW_TRANSFORM parameters.

Or disable these parameters by default.

Cheers,
Uwe

**Comment by pgoldtho** [comment]
Which doc do you think we should add this to? Updating the readme is easy to do. Let me know what you want it to say and 
I can update it or submit a pull request if you prefer. 

This is the file that controls the default values:

https://github.com/visulate/visulate-ora2pg/blob/main/express/resources/ora2pg-conf.json

I copied the defaults from ora2pg when I created it. It should be a simple change if you want to update it

**Comment by oraculix** [comment]
Thanks for the prompt answer, Peter.
Having thought about it a bit longer, my opinion changed: As this is the default setting of ora2pg, it is also not something that should be explicitly documented in visulate-ora2pg.

From my perspective, we can close this issue.
