### ISSUE TITLE
Move target connection (pg) test to top

### ISSUE THREAD

**Issue by pkej** [visulate/visulate-ora2pg#59]
It gets a bit tedious to wait for the information that the connection to pg failed. It would be great knowing that early.

Apart from that, it seems to work pretty well, still setting up the move from oracle to pg, but I got the tables up, which is better than what I had.

**Comment by pgoldtho** [comment]
Added PG_DSN, PG_USER and PG_PWD to basic settings

**Comment by pkej** [comment]
Hmm, I guess it is the ora2pg.darold.net, sorry bout that. Great that you added the PG_DSN etc. to basic settings.

**Comment by pgoldtho** [comment]
@pkej just released a new version 1.2.0. It moves the database credentials to session storage. It also validates credentials before starting a run. See: https://github.com/visulate/visulate-ora2pg/blob/main/specs/auth_requirements.md
